export class Newappointment{
  public constructor(
    public Id:number,
    public fname:string,
    public lname:string,
    public dob:any,
    public gender:string,
    public  name:string,
    public  phonenum:any,
    public relationship:string,
    public cell:string,
    public home:string,
    public work:string,
    public preference:string,
    public email:string,
    public appointmenttype:string,
    public provider:string,
    public dateofservice:string,
    public casetype:string,
    public incidenttype:string,
    public dateofaccident:string,
    public accidentzip:string,
    public accidentstate:string,
    public accidentcity:string,
    public address1:string,
    public address2:string,
    public zip:string,
    public city:string,
    public state:string,
    public ssn:string,
    public language:string,
    public email1:string,
    public phone:string,
    public text:string,

  ){}
}
